dist: xenial

language: go

go:
  - "1.12.x"

sudo: true

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - sudo apt-get install beignet-dev nvidia-cuda-dev nvidia-cuda-toolkit
  - sudo apt-get install cargo -y

env:
  - GO111MODULE=on

script:
  - cd lib/cuckoo && cargo build --release && cd ../../ && export LD_LIBRARY_PATH=`pwd`/target/release:$LD_LIBRARY_PATH && ./ci.sh