os: osx

language: go

go:
  - "1.12.x"

sudo: true

install:
  - brew install rust
  - brew install FiloSottile/musl-cross/musl-cross
  - brew install mingw-w64
  - rustup target add x86_64-pc-windows-gnu
  - rustup target add x86_64-unknown-linux-musl
  - rustup target add x86_64-apple-darwin

env:
  - GO111MODULE=on

script:
  - sh multi-cross.sh

deploy:
  provider: releases
  api_key:
    secure: [token]
  file: *.zip
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
