dist: xenial
matrix:
  include:
    - language: rust
      rust:
        - stable
      sudo: false
      script:
        - cd lib/cuckoo && cargo build --release && cp target/release/libcuckoo.so /usr/lib/libcuckoo.so

    - language: go

      go:
        - "1.12.x"

      sudo: false

      install:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
        - sudo apt-get install beignet-dev nvidia-cuda-dev nvidia-cuda-toolkit
        - curl https://sh.rustup.rs -sSf | sh

      env:
        - GO111MODULE=on

      script:
        - ./ci.sh


