dist: xenial

language: go

go:
  - "1.12.x"

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - sudo apt-get install cargo -y

env:
  - GO111MODULE=on

script:
  - cd lib/cuckoo && cargo build --release && cd ../../ && wget https://github.com/jamesvan2019/OpenCL-ICD-Loader/releases/download/v0.0.1/libOpenCL.zip && unzip libOpenCL.zip -d lib/opencl/ && ./ci.sh